insert into pauta(id, nome) values
(1, "PRESTAÇÃO DE CONTAS DE PARTIDO POLÍTICO"),
(2, "PRESTAÇÃO DE CONTAS DE ÓRGÃO DE DIREÇÃO REGIONAL"),
(3, "PEDIDO DE PROVIDÊNCIAS"),
(4, "RECURSO CRIMINAL - FALSIDADE IDEOLÓGICA"),
(5, "RECURSO ELEITORAL - CAPTAÇÃO OU GASTO ILÍCITO DE RECURSOS FINANCEIROS DE CAMPANHA ELEITORAL"),
(6, "ABUSO DE PODER ECONÔMICO - PEDIDO DE PROVIDÊNCIAS");